# Use official Python base image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy script into container
COPY app.py .

# Run Python script when container starts
CMD ["python", "app.py"]
