service: nest-lambda-service

frameworkVersion: '>= 4.*.*'

provider:
  name: aws
  runtime: nodejs18.x
  logs:
    httpApi: true
  region: us-east-1
  stage: dev
  memorySize: 512
  timeout: 10 # seconds (max is 900 for async lambdas)   
  environment:
    MONGODB_URI: ${env:MONGODB_URI}
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    DB_USERNAME: ${env:DB_USERNAME}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_NAME: ${env:DB_NAME}

functions:
  api:
    handler: dist/lambda.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-offline

package:
  individually: true
  excludeDevDependencies: true

custom:
  serverless-offline:
    httpPort: 3000
    noPrependStageInUrl: true
