service: my-lambda-a

frameworkVersion: '>= 4.*.*'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev
  memorySize: 512
  timeout: 10
  environment:
    MONGODB_URI: your-mongodb-uri-here
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sns:Publish
          Resource: "*"

functions:
  api:
    handler: dist/lambda.handler
    events:
      - httpApi: '*'
  app:
    handler: dist/main.handler
    events:
      - sns: arn:aws:sns:us-east-1:123456789012:MyLambdaTopic

plugins:
  - serverless-offline

package:
  individually: true
  excludeDevDependencies: true
  exclude:
    - node_modules/**
    - test/**

custom:
  serverless-offline:
    httpPort: 3000
    noPrependStageInUrl: true
