service: nest-lambda-service

frameworkVersion: '>= 4.*.*'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev
  memorySize: 512
  timeout: 10
  environment:
    MONGODB_URI: mongodb+srv://werttt:qwertyu@cluster0.hlicuim.mongodb.net/demodb?retryWrites=true&w=majority
    DB_HOST: mylambdadb.cap2ummaswr9.us-east-1.rds.amazonaws.com
    DB_PORT: 3306
    DB_USERNAME: admin
    DB_PASSWORD: Lnsel$345CFL
    DB_NAME: test

functions:
  api:
    handler: dist/lambda.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-offline

package:
  individually: true
  excludeDevDependencies: true

custom:
  serverless-offline:
    httpPort: 3000
    noPrependStageInUrl: true
