service: lambdasns01

frameworkVersion: '>= 4.*.*'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev
  memorySize: 512
  timeout: 10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:Subscribe
        - sns:Receive
        - sns:Publish
      Resource: arn:aws:sns:us-east-1:466015320752:MySNSTopic
  environment:
    MONGODB_URI: your-mongodb-uri-here

functions:
  api:
    handler: dist/lambda.handler
    events:
      - httpApi: '*'
      - sns:
          arn: arn:aws:sns:us-east-1:466015320752:MySNSTopic      

plugins:
  - serverless-offline

package:
  individually: true
  excludeDevDependencies: true

custom:
  serverless-offline:
    httpPort: 3000
    noPrependStageInUrl: true
