service: lambda04

#frameworkVersion: '^3.0.0'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: dev
  memorySize: 512
  timeout: 10
  environment:
    MONGODB_URI: your-mongodb-uri-here
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
        - sqs:GetQueueAttributes
      Resource: arn:aws:sqs:us-east-1:466015320752:lambdaproductcreate.fifo

functions:
  api:
    handler: dist/lambda.handler
    events:
      - httpApi: '*'
#  sqsHandler:
#    handler: dist/main.handler
#    events:
#      - sqs:
#          arn: arn:aws:sqs:us-east-1:466015320752:lambdaproductcreate.fifo
#          batchSize: 1
#          maximumRetryAttempts: 2

# plugins:
#   - serverless-offline

package:
  individually: true
  patterns:
    - 'dist/**'
    - 'src/templates/**'
    - 'public/**'
    - 'node_modules/**'
    - '!node_modules/@types/**'
    - '!node_modules/typescript/**'
    - '!node_modules/@typescript-eslint/**'
    - '!node_modules/eslint/**'
    - '!node_modules/prettier/**'
    - '!node_modules/jest/**'
    - '!node_modules/@jest/**'
    - '!node_modules/ts-jest/**'
    - '!node_modules/ts-node/**'
    - '!node_modules/ts-loader/**'
    - '!node_modules/@nestjs/cli/**'
    - '!node_modules/@nestjs/schematics/**'
    - '!node_modules/@nestjs/testing/**'
    - '!node_modules/serverless/**'
    - '!node_modules/serverless-offline/**'
    - '!node_modules/esbuild/**'
    - '!node_modules/supertest/**'

custom:
  serverless-offline:
    httpPort: 3000
    noPrependStageInUrl: true
