service: nest-lambda-service

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  memorySize: 512
  timeout: 10
  stage: dev


functions:
  api:
    handler: dist/main.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: node18
    platform: node
    exclude: ['aws-sdk']
    concurrency: 10
