# SonarQube configuration
sonar.projectKey=usercrud
sonar.projectName=Node Express CRUD API
sonar.projectVersion=1.0
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=node_modules/**,dist/**
