sonar.projectKey=productcrud
sonar.projectName=productcrud
sonar.projectVersion=1.0

sonar.sources=.
sonar.language=js
sonar.sourceEncoding=UTF-8

# SonarQube server (running in Docker on your host)
sonar.host.url=http://sonarqube:9000

# Token (from Step 2)
sonar.login=sqp_57f47afbea06ba68044260d91bc7a73b265ce072

















# sonar.projectKey=ProductCrud
# sonar.projectName=ProductCRUD
# sonar.projectVersion=1.0
# sonar.sources=.




# sonar.projectKey=product-crud
# sonar.projectName=product-crud
# sonar.projectVersion=1.0

# sonar.sources=.
# sonar.exclusions=node_modules/**,coverage/**
# sonar.language=js

# sonar.host.url=http://sonarqube:9000
# sonar.login=squ_8e9fdee2b953c191069e9061f3cf4aafa8ab1aef

# sonar.javascript.lcov.reportPaths=coverage/lcov.info





# # --- Identification
# sonar.projectKey=product-crud
# sonar.projectName=product-crud
# sonar.sourceEncoding=UTF-8

# # --- Sources & tests
# sonar.sources=.
# sonar.exclusions=**/node_modules/**,coverage/**,**/*.test.js
# sonar.tests=.
# sonar.test.inclusions=**/*.test.js

# # --- Coverage (Jest produces LCOV)
# sonar.javascript.lcov.reportPaths=coverage/lcov.info
