# Thymeleaf Configuration
spring.thymeleaf.cache=false

# Security Configuration
spring.security.user.name=admin
spring.security.user.password=admin
spring.security.user.roles=ADMIN

# Server Configuration
server.port=8080
