@baseUrl = http://localhost:3001
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3ODI4MDEwNzAsImV4cCI6MTc4MjgwNDY3MH0.9S4DeIWynKNKaogjyOAI_mWLxSVrt3dWySNKotcq748
# @token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoidXNlckB0ZXN0LmNvbSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzgyNzIxMzQ3LCJleHAiOjE3ODI3MjQ5NDd9.3_x0-cVwWL3eIS5N5hgwhQNR-1uN7YZkqHqXw4QPyWQ

### =====================================
### CREATE TOKEN (Admin)
### =====================================

POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "admin123"
}


### =====================================
### CREATE TOKEN (User)
### =====================================

POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "user@test.com",
  "password": "user123"
}

### =====================================
### PRODUCTS API
### =====================================

### Get All Products (Public)
GET {{baseUrl}}/products

###

### Get Product By ID (Protected)
GET {{baseUrl}}/products/1
Authorization: Bearer {{token}}

###

### Create Product (Protected)
POST {{baseUrl}}/products
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Dummy Three Laptop",
  "price": 55000
}

###

### Update Product (Protected)
PUT {{baseUrl}}/products/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Gaming NewTwo Laptop",
  "price": 75000
}

###

### Delete Product (Protected)
DELETE {{baseUrl}}/products/1
Authorization: Bearer {{token}}