name: Deploy NestJS to Cloud Run

on:
  push:
    branches:
      - grpc_order

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: terraform-497011
      REGION: asia-south1
      SERVICE: order-service
      REPOSITORY: nestjs-repo
      IMAGE: asia-south1-docker.pkg.dev/terraform-497011/nestjs-repo/nestjs

    steps:
      # ----------------------------------
      # Checkout Repository
      # ----------------------------------
      - name: Checkout Repository
        uses: actions/checkout@v4

      # ----------------------------------
      # Authenticate Google Cloud
      # ----------------------------------
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # ----------------------------------
      # Setup gcloud
      # ----------------------------------
      - name: Setup gcloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # ----------------------------------
      # Configure Docker
      # ----------------------------------
      - name: Configure Docker
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet

      # ----------------------------------
      # Setup Node.js
      # ----------------------------------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      # ----------------------------------
      # Install Dependencies
      # ----------------------------------
      - name: Install Dependencies
        run: npm ci

      # ----------------------------------
      # Generate Prisma Client
      # ----------------------------------
      - name: Generate Prisma Client
        run: npx prisma generate

      # ----------------------------------
      # Build NestJS
      # ----------------------------------
      - name: Build Project
        run: |
          npm run build

          echo "===== Build Exit Code ====="
          echo $?

          echo "===== Project Root ====="
          ls -lah

          echo "===== dist ====="
          ls -lah dist || true

          echo "===== Nest Info ====="
          npx nest info

      # ----------------------------------
      # Verify Build Output
      # ----------------------------------
      - name: Verify Build Output
        run: |
          echo "===== Current Directory ====="
          pwd

          echo "===== Files ====="
          find . -name main.js

          echo "===== dist ====="
          find dist -type f

          test -f dist/src/main.js

      # ----------------------------------
      # Build Docker Image
      # ----------------------------------
      - name: Build Docker Image
        run: |
          docker build \
            --pull \
            --no-cache \
            -t $IMAGE:${{ github.sha }} .

      # ----------------------------------
      # Verify Docker Image
      # ----------------------------------
      - name: Verify Docker Image
        run: |
          docker run --rm \
            $IMAGE:${{ github.sha }} \
            sh -c "
              echo '===== Runtime ====='
              pwd

              echo '===== /app ====='
              ls -lah

              echo '===== /app/dist ====='
              ls -lah /app/dist

              echo '===== Compiled Files ====='
              find /app/dist -type f

              test -f /app/dist/src/main.js
            "

      # ----------------------------------
      # Verify Runtime Files
      # ----------------------------------
      - name: Verify Runtime Files
        run: |
          docker run --rm \
            $IMAGE:${{ github.sha }} \
            sh -c "
              echo '========================================'
              echo 'Current Directory'
              pwd

              echo '========================================'
              echo '/app/dist'
              find /app/dist -type f

              echo '========================================'
              echo '/app/dist/src'
              find /app/dist/src -type f
            "

      # ----------------------------------
      # Start Docker Container
      # ----------------------------------
      - name: Run Docker Container
        run: |
          docker run -d \
            --name nest-test \
            -p 8080:8080 \
            -e NODE_ENV=production \
            -e GRPC_URL=0.0.0.0:50051 \
            -e DATABASE_URL="${{ secrets.NEON_POSTGRE_DATABASE_URL_NEW }}" \
            -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            $IMAGE:${{ github.sha }}

          echo "Waiting for application..."
          sleep 20

          echo "===== Running Containers ====="
          docker ps

          echo "===== Container Logs ====="
          docker logs nest-test

          echo "===== HTTP Test From Host ====="
          curl --fail --show-error --silent http://localhost:8080/getdata

          echo
          echo "===== HTTP Test Inside Container ====="
          # docker exec nest-test wget -qO- http://localhost:8080/getdata
          docker exec nest-test sh -c "wget -S -O- http://127.0.0.1:8080/getdata"

          echo
          echo "===== Final Container Logs ====="
          docker logs nest-test

          docker stop nest-test

      # ----------------------------------
      # Push Docker Image
      # ----------------------------------
      - name: Push Docker Image
        run: |
          docker push $IMAGE:${{ github.sha }}

      # ----------------------------------
      # Verify Artifact Registry Image
      # ----------------------------------
      - name: Verify Artifact Image
        run: |
          gcloud artifacts docker images describe \
            $IMAGE:${{ github.sha }}

      # ----------------------------------
      # Deploy Cloud Run
      # ----------------------------------
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE \
            --image $IMAGE:${{ github.sha }} \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated \
            --port 8080 \
            --service-account cloudrun@terraform-497011.iam.gserviceaccount.com \
            --set-env-vars DATABASE_URL="${{ secrets.NEON_POSTGRE_DATABASE_URL_NEW }}" \
            --set-env-vars JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            --set-env-vars NODE_ENV=production \
            --set-env-vars GRPC_URL=0.0.0.0:50051

      - name: Show Cloud Run Logs
        run: |
          gcloud logging read \
            'resource.type="cloud_run_revision" AND resource.labels.service_name="'$SERVICE'"' \
            --limit=100 \
            --freshness=30m \
            --format="value(textPayload)"

      - name: Show Cloud Run Logs
        if: failure()
        run: |
          echo "===== Cloud Run Logs ====="

          gcloud logging read \
            "resource.type=cloud_run_revision AND resource.labels.service_name=$SERVICE" \
            --limit=200 \
            --freshness=30m \
            --format="table(timestamp,severity,textPayload)"


      - name: Show Project Logs
        if: always()
        run: |
          gcloud logging read \
            --project=$PROJECT_ID \
            --limit=100 \
            --freshness=30m


      - name: Show Cloud Run Errors
        if: always()
        run: |
          gcloud logging read \
            'resource.type="cloud_run_revision"
            AND resource.labels.service_name="'$SERVICE'"
            AND severity>=ERROR' \
            --project=$PROJECT_ID \
            --limit=100 \
            --freshness=30m


      # ----------------------------------
      # Print Service URL
      # ----------------------------------
      - name: Get Service URL
        run: |
          echo "===== Cloud Run URL ====="

          gcloud run services describe $SERVICE \
            --region $REGION \
            --format="value(status.url)"

      # ----------------------------------
      # Print Cloud Run Configuration
      # ----------------------------------
      - name: Verify Cloud Run Configuration
        run: |
          echo "===== Cloud Run Service ====="

          gcloud run services describe $SERVICE \
            --region $REGION \
            --format="yaml(spec.template.spec.containers)"


      # ----------------------------------
      # Test Cloud Run Endpoint
      # ----------------------------------
      - name: Test Cloud Run Endpoint
        run: |
          SERVICE_URL=$(gcloud run services describe $SERVICE \
            --region $REGION \
            --format="value(status.url)")

          echo "===== Service URL ====="
          echo "$SERVICE_URL"

          echo "===== Waiting for Cloud Run ====="
          sleep 15

          echo "===== GET /getdata ====="
          curl --fail \
              --show-error \
              --silent \
              --location \
              "$SERVICE_URL/getdata"

          echo
          echo "✅ Cloud Run endpoint is working."

      # ----------------------------------
      # Cloud Run Logs
      # ----------------------------------
      - name: Show Cloud Run Logs
        if: always()
        run: |
          echo "========================================"
          echo "Cloud Run Logs"
          echo "========================================"

          gcloud beta run services logs read $SERVICE \
            --region $REGION \
            --limit=100


      # ----------------------------------
      # Test Cloud Run Endpoint
      # ----------------------------------
      - name: Test Cloud Run
        run: |
          URL=$(gcloud run services describe $SERVICE \
            --region $REGION \
            --format="value(status.url)")

          echo "========================================"
          echo "Cloud Run URL:"
          echo "$URL"
          echo "========================================"

          echo "Waiting for deployment..."
          sleep 20

          echo "========================================"
          echo "GET /getdata"
          echo "========================================"

          curl -v \
            --fail \
            --show-error \
            --location \
            "$URL/getdata"



      - name: Test Cloud Run
        run: |
          URL=$(gcloud run services describe $SERVICE \
            --region $REGION \
            --format="value(status.url)")

          echo "URL=$URL"

          sleep 20

          echo "===== Response ====="
          curl -v "$URL/getdata"