name: Deploy to AWS Lambda using Serverless

on:
  push:
    branches:
      - lambda_01_cicd_03  # Change to your deployment branch if needed
      - graphQL  # Change to your deployment branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use the version you're developing with

      - name: Install Dependencies
        run: npm ci

      - name: Install Serverless Framework v3
        run: npm install -g serverless@3

      - name: Build
        run: npm run build # or nest build

      - name: Deploy with Serverless
        run: npx serverless deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
