name: Deploy NestJS to Cloud Run

on:
  push:
    branches:
      - revest-api-gateway

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: terraform-497011
      REGION: asia-south1
      SERVICE: revest-api-gateway
      REPOSITORY: nestjs-repo
      IMAGE: asia-south1-docker.pkg.dev/terraform-497011/nestjs-repo/nestjs

    steps:
      # ----------------------------------
      # Checkout
      # ----------------------------------
      - name: Checkout Repository
        uses: actions/checkout@v4

      # ----------------------------------
      # Authenticate Google Cloud
      # ----------------------------------
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # ----------------------------------
      # Setup gcloud
      # ----------------------------------
      - name: Setup gcloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # ----------------------------------
      # Configure Docker
      # ----------------------------------
      - name: Configure Docker
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet

      # ----------------------------------
      # Setup Node.js
      # ----------------------------------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      # ----------------------------------
      # Install Dependencies
      # ----------------------------------
      - name: Install Dependencies
        run: npm ci

      # ----------------------------------
      # Build NestJS
      # ----------------------------------
      - name: Build Project
        run: |
          npm run build

          echo "===== Exit Code ====="
          echo $?

          echo "===== Root ====="
          ls -la

          echo "===== dist ====="
          ls -la dist || true

          echo "===== Nest CLI ====="
          npx nest info

      # ----------------------------------
      # Verify Build Output
      # ----------------------------------
      - name: Verify Build Output
        run: |
          echo "===== Current Directory ====="
          pwd

          echo "===== Project Root ====="
          ls -lah

          echo "===== src ====="
          ls -lah src || true

          echo "===== dist ====="
          ls -lah dist || true

          echo "===== Files inside dist ====="
          find dist -type f || true

          echo "===== Searching main.js ====="
          find . -name main.js

          if [ ! -f dist/src/main.js ]; then
            echo "ERROR: dist/src/main.js not found!"
            exit 1
          fi

      # ----------------------------------
      # Build Docker Image
      # ----------------------------------
      - name: Build Docker Image
        run: |
          docker build \
            --pull \
            --no-cache \
            -t $IMAGE:${{ github.sha }} .

      # ----------------------------------
      # Verify Docker Image
      # ----------------------------------
      - name: Verify Docker Image
        run: |
          docker run --rm $IMAGE:${{ github.sha }} sh -c "
            echo '===== DIST =====';
            find /app/dist -type f;

            echo '===== PROTO =====';
            ls -lah /app/dist/src/proto || true;

            echo '===== ITEM PROTO =====';
            test -f /app/dist/src/proto/item.proto            
          "

      # ----------------------------------
      # Push Image
      # ----------------------------------
      - name: Push Docker Image
        run: |
          docker push $IMAGE:${{ github.sha }}

      # ----------------------------------
      # Verify Artifact Registry Image
      # ----------------------------------
      - name: Verify Artifact Image
        run: |
          gcloud artifacts docker images describe $IMAGE:${{ github.sha }}

      # ----------------------------------
      # Deploy Cloud Run
      # ----------------------------------
      - name: Verify Order Service
        run: |
          echo "========================================"
          echo "ORDER SERVICE"
          echo "========================================"

          gcloud run services describe revest-order-service \
            --region=$REGION \
            --format="yaml(status.url,status.conditions)"

          echo
          echo "========================================"
          echo "LATEST REVISION"
          echo "========================================"

          gcloud run revisions list \
            --service=revest-order-service \
            --region=$REGION \
            --limit=5

          echo
          echo "========================================"
          echo "RECENT LOGS"
          echo "========================================"

          gcloud logging read \
            'resource.type="cloud_run_revision" AND resource.labels.service_name="revest-order-service"' \
            --limit=20 \
            --freshness=30m \
            --format="table(timestamp,severity,textPayload)"


      - name: Verify Order Service
        run: |
          echo "========================================"
          echo "ORDER SERVICE DETAILS"
          echo "========================================"

          gcloud run services describe revest-order-service \
            --region=$REGION \
            --format="yaml(
              metadata.name,
              status.url,
              status.conditions,
              spec.template.spec.containers
            )"

          echo
          echo "========================================"
          echo "ORDER SERVICE TRAFFIC"
          echo "========================================"

          gcloud run services describe revest-order-service \
            --region=$REGION \
            --format="value(status.traffic)"


      - name: Test Order Service URL
        run: |
          echo "Checking DNS..."
          nslookup revest-order-service-334684044157.asia-south1.run.app || true
          echo
          curl -I https://revest-order-service-tefwbu3cwa-el.a.run.app || true

      - name: Describe Order Service
        run: |
          gcloud run services describe revest-order-service \
            --region=$REGION \
            --format="value(status.address.url)"



      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE \
            --image $IMAGE:${{ github.sha }} \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated \
            --port 3001 \
            --service-account cloudrun@terraform-497011.iam.gserviceaccount.com \
            --set-env-vars NODE_ENV=production \
            --set-env-vars ITEM_GRPC_URL=dns:///revest-item-service-334684044157.asia-south1.run.app:443 \
            --set-env-vars ORDER_GRPC_URL=dns:///revest-order-service-334684044157.asia-south1.run.app:443 \
            --set-env-vars JWT_SECRET="${{ secrets.JWT_SECRET }}"


      # ----------------------------------
      # Print Cloud Run Logs on Failure
      # ----------------------------------
      - name: Print Cloud Run Logs
        if: failure()
        run: |
          echo "===== Cloud Run Logs ====="

          gcloud logging read \
            'resource.type="cloud_run_revision"
            resource.labels.service_name="revest-api-gateway"' \
            --limit=100 \
            --order=desc \
            --format="table(timestamp,severity,textPayload)"


      # ----------------------------------
      # Service URL
      # ----------------------------------
      - name: Get Service URL
        run: |
          gcloud run services describe $SERVICE \
            --region $REGION \
            --format="value(status.url)"


      - name: Test Orders Endpoint
        run: |
          echo "===== GET /orders ====="

          curl -v \
            https://revest-api-gateway-tefwbu3cwa-el.a.run.app/api/orders

      - name: API Gateway Logs
        if: always()
        run: |
          gcloud logging read \
            'resource.type="cloud_run_revision" AND resource.labels.service_name="revest-api-gateway"' \
            --limit=50 \
            --freshness=10m \
            --format="table(timestamp,severity,textPayload)"