name: Deploy to AWS Lambda via Serverless

on:
  push:
    branches:
      - main  # Change to your default branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install NPM dependencies
        run: npm ci

      - name: Install Serverless Framework v3 (no login required)
        run: npm install -g serverless@3

      - name: Deploy with Serverless
        run: serverless deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
